/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control_casos.ui;

/**
 *
 * @author Asael
 */
public class AdministradorProyectoUI extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorProyectoUI
     */
    public AdministradorProyectoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCaso = new javax.swing.JDialog();
        txtIdProyecto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIdCaso = new javax.swing.JFormattedTextField();
        btnRegistrarC = new javax.swing.JButton();
        btnActualizarC = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        txtFechaLimite = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProyectosAP = new javax.swing.JMenu();
        itemProyectoAsig = new javax.swing.JMenuItem();
        menuCasoAP = new javax.swing.JMenu();
        itemCrearCaso = new javax.swing.JMenuItem();
        itemCancelarCaso = new javax.swing.JMenuItem();
        menuEtapaAP = new javax.swing.JMenu();
        itemVerificarWork = new javax.swing.JMenuItem();

        dialogCaso.setSize(new java.awt.Dimension(530, 440));

        jLabel6.setText("Id Caso");

        btnRegistrarC.setText("Registrar");

        btnActualizarC.setText("Actualzar");

        btnEliminar.setText("jButton3");

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Fecha Inicio");

        jLabel4.setText("Fecha Limite");

        jLabel5.setText("Id Proyecto");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Proyecto", "Tipo Caso", "Feha Inicio", "Fecha Limite"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout dialogCasoLayout = new javax.swing.GroupLayout(dialogCaso.getContentPane());
        dialogCaso.getContentPane().setLayout(dialogCasoLayout);
        dialogCasoLayout.setHorizontalGroup(
            dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCasoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogCasoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogCasoLayout.createSequentialGroup()
                        .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dialogCasoLayout.createSequentialGroup()
                                .addComponent(txtIdCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(btnRegistrarC)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarC)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addGroup(dialogCasoLayout.createSequentialGroup()
                                .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechaInicio)
                                    .addComponent(txtIdProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane3))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        dialogCasoLayout.setVerticalGroup(
            dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCasoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarC)
                    .addComponent(btnActualizarC)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuProyectosAP.setText("Proyectos");

        itemProyectoAsig.setText("Proyectos Asignados");
        menuProyectosAP.add(itemProyectoAsig);

        jMenuBar1.add(menuProyectosAP);

        menuCasoAP.setText("Casos");

        itemCrearCaso.setText("Crear Caso");
        menuCasoAP.add(itemCrearCaso);

        itemCancelarCaso.setText("Cancelar Caso");
        menuCasoAP.add(itemCancelarCaso);

        jMenuBar1.add(menuCasoAP);

        menuEtapaAP.setText("Etapa");

        itemVerificarWork.setText("Verificar Trabajo Desarrollador");
        menuEtapaAP.add(itemVerificarWork);

        jMenuBar1.add(menuEtapaAP);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarC;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrarC;
    private javax.swing.JDialog dialogCaso;
    private javax.swing.JMenuItem itemCancelarCaso;
    private javax.swing.JMenuItem itemCrearCaso;
    private javax.swing.JMenuItem itemProyectoAsig;
    private javax.swing.JMenuItem itemVerificarWork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu menuCasoAP;
    private javax.swing.JMenu menuEtapaAP;
    private javax.swing.JMenu menuProyectosAP;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JFormattedTextField txtFechaLimite;
    private javax.swing.JFormattedTextField txtIdCaso;
    private javax.swing.JTextField txtIdProyecto;
    private javax.swing.JTextField txtNombreC;
    // End of variables declaration//GEN-END:variables
}
