/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control_casos.ui;

/**
 *
 * @author Asael
 */
public class DesarrolladorUI extends javax.swing.JFrame {

    /**
     * Creates new form DesarrolladorUI
     */
    public DesarrolladorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogDesarrollador = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCasosD = new javax.swing.JMenu();
        itemCasosAsig = new javax.swing.JMenuItem();
        menuEtapaD = new javax.swing.JMenu();
        itemRepFin = new javax.swing.JMenuItem();

        dialogDesarrollador.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout dialogDesarrolladorLayout = new javax.swing.GroupLayout(dialogDesarrollador.getContentPane());
        dialogDesarrollador.getContentPane().setLayout(dialogDesarrolladorLayout);
        dialogDesarrolladorLayout.setHorizontalGroup(
            dialogDesarrolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        dialogDesarrolladorLayout.setVerticalGroup(
            dialogDesarrolladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCasosD.setText("Casos");

        itemCasosAsig.setText("Casos Asignados");
        menuCasosD.add(itemCasosAsig);

        jMenuBar1.add(menuCasosD);

        menuEtapaD.setText("Etapa");

        itemRepFin.setText("Reportar Finalizacion");
        menuEtapaD.add(itemRepFin);

        jMenuBar1.add(menuEtapaD);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogDesarrollador;
    private javax.swing.JMenuItem itemCasosAsig;
    private javax.swing.JMenuItem itemRepFin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCasosD;
    private javax.swing.JMenu menuEtapaD;
    // End of variables declaration//GEN-END:variables
}
